# Generated by Django 4.0.5 on 2022-06-25 21:07

import creditcards.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bankaccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', creditcards.models.CardNumberField(max_length=25)),
                ('password_account', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('ammount', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=50)),
                ('bankaccount', creditcards.models.CardNumberField(max_length=25)),
                ('bankpassword', models.CharField(max_length=20)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('is_online', models.BooleanField(default=False)),
                ('code', models.DecimalField(decimal_places=0, max_digits=6)),
                ('created', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offername', models.CharField(max_length=50)),
                ('model_year', models.IntegerField()),
                ('brand', models.CharField(max_length=50)),
                ('startingbet', models.DateField()),
                ('endingbet', models.DateField()),
                ('imgurl1', models.ImageField(upload_to='')),
                ('imgurl2', models.ImageField(upload_to='')),
                ('imgurl3', models.ImageField(upload_to='')),
                ('imgurl4', models.ImageField(upload_to='')),
                ('imgurl5', models.ImageField(upload_to='')),
                ('imgurl6', models.ImageField(upload_to='')),
                ('initialprice', models.DecimalField(decimal_places=10, max_digits=20)),
                ('finalprice', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.users')),
            ],
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.DecimalField(decimal_places=10, max_digits=20)),
                ('date', models.DateField()),
                ('is_win', models.BooleanField(default=False)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.offer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.users')),
            ],
        ),
    ]
