# Generated by Django 4.0.5 on 2022-06-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_remove_users_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='endingbet',
            field=models.DateTimeField(),
        ),
    ]
